/**
 * FastScore API (proxy)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.opendatagroup.fastscore.swagger.models2


case class ActiveModelInfo (
  name: Option[String],
  mtype: Option[String],
  source: Option[String],
  slots: Option[List[SlotInfo]],
  attachments: Option[List[String]],
  snapshots: Option[String],
  jets: Option[List[JetInfo]]
)

