FROM alpine

RUN apk add --no-cache bash curl shadow make py-setuptools openjdk8-jre

RUN curl -L https://github.com/krallin/tini/releases/download/v0.17.0/tini-muslc-amd64 > /tini && chmod +x /tini
ENTRYPOINT ["/tini", "--"]

ARG uid
ARG gid
RUN groupadd -fg $gid user && useradd -o -m -u $uid -g $gid user
USER user

RUN mkdir -p ~/bin &&\
	curl http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.3/swagger-codegen-cli-2.2.3.jar > ~/bin/swagger-codegen-cli.jar

WORKDIR /_
