/**
 * FastScore API (proxy)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.opendatagroup.fastscore.swagger.models1


case class CpuUsageInfoOpTimes (
  unwrapEnvelope: Option[Number],
  unwrapEnvelopeN: Option[Number],
  wrapEnvelope: Option[Number],
  wrapEnvelopeN: Option[Number],
  decodeInputRecord: Option[Number],
  decodeInputRecordN: Option[Number],
  typeCheckInput: Option[Number],
  typeCheckInputN: Option[Number]
)

