/**
 * FastScore API (proxy)
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.opendatagroup.fastscore.swagger.models1


case class CpuUsageInfo (
  duration: Option[Number],
  inputBytes: Option[Integer],
  inputRecords: Option[Integer],
  outputBytes: Option[Integer],
  outputRecords: Option[Integer],
  userTime: Option[Number],
  kernelTime: Option[Number],
  opTimes: Option[List[CpuUsageInfoOpTimes]],
  jets: Option[List[CpuUsageInfoJets]]
)

