fastscore:
  fleet:
    - api: model-manage
      host: model-manage
      port: 8002
    - api: engine
      host: engine-1
      port: 8003
    - api: engine
      host: engine-2
      port: 8003

  db:
    type: mysql
    host: database
    port: 3306
    username: root
    password: root

  pneumo:
    type: kafka
    bootstrap:
      - kafka:9092
    topic: notify
