---
title: "R Notebook"
output: html_notebook
---

Most imports are from local library directory, change path accordingly.
```{r}
lib <- "/Users/nanshi/Documents/GitHub/fastscore/library/"

library("GotoRFastscore")
GotoRFastscore::Connect("https://localhost:8000")
Config_set("/Users/nanshi/Documents/Github/fastscore/config.yaml")
Sys.sleep(5) #give system time to load configuration
Get_Fleet()
Config_show()
```

```{r}
import(list("emit-attach1.py3", "echo-array-double.R"), "model", lib)
Model_list()
Model_show("echo-array-double.R")
Model_remove("echo-array-double.R")
```
```{r}
import(list("array-double", "string", "close"), "schema", lib)
Schema_list()
Schema_show("close")
Schema_remove("close")
```
```{r}
import(list("array-double-input", "string-output", "array-double-output"), "stream", lib)
Stream_list()
Stream_show("array-double-output")

Stream_attach(1, "array-double-output", "engine-1")
Stream_detach(1, "engine-1")
Stream_remove("array-double-output")
```

```{r}
Modelname <- "emit-attach1.py3"

Attname <- "file-contains-1234.tgz"
dir <- paste(lib, "attachments/", Attname, sep = "")
Attachment_upload(Modelname, Attname, dir)

Attname <- "file-contains-abcd.tgz"
dir <- paste(lib, "attachments/", Attname, sep = "")
Attachment_upload(Modelname, Attname, dir)
Attachment_list(Modelname)

dir <- paste(lib, "downloads/", Attname, sep = "")
Attachment_download(Modelname, Attname, dir)
Attachment_remove(Modelname, Attname)
```

```{r}
Stream_attach(0, "array-double-input", "engine-1")
Stream_sample("array-double-input", "engine-1", 5)
Stream_attach(1, "string-output", "engine-1")
Model_load("emit-attach1.py3", "engine-1")
```

```{r}
Engine_inspect("engine-1")
Engine_pause("engine-1")
Engine_unpause("engine-1")
Engine_reset("engine-1")
Run("engine-1", "emit-attach1.py3", "array-double-input", "string-output")
```
```{r}
Engine_reset("all")
remove_all("model")
remove_all("schema")
remove_all("stream")
```

