---
title: "Introduction to fastscoRe"
author: "Chris Comiskey"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}\
  
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

Three [pillars](https://opendatagroup.github.io/Reference/FastScore%20API/). 

- Connect
- Model Manage
- Engine

All inherit from initial FastScore API instance. 

## Instance Class

Create FastScore API client with `Instance` class generator.

```{r, eval = FALSE}
> api_cli <- fastscoRe::Instance$new(basePath = "https://localhost:8000")
> api_cli
<Instance>
  Public:
    basePath: https://localhost:8000/api/1/service
    callApi: function (url, method, queryParams, headerParams, body, ...) 
    clone: function (deep = FALSE) 
    configuration: NULL
    defaultHeaders: NULL
    initialize: function (basePath, configuration, defaultHeaders) 
    userAgent: Swagger-Codegen/1.0.0/r
```

## Connect Class

FastScore Connect  [documentation](https://opendatagroup.github.io/Reference/FastScore%20API/Connect/)

```{r, eval = FALSE}
> con <- fastscoRe::Connect$new(apiClient = api_cli)
> con
<Connect>
  Public:
    ...

> con$health_get(instance = "connect")$response
Response [https://localhost:8000/api/1/service/connect/1/health]
  Date: 2018-10-04 18:48
  Status: 200
  Content-Type: application/json
  Size: 103 B

>   resp <- con$health_get(instance = "connect")$response
>   httr::content(resp)
$release
[1] "1.7"

$id
[1] "6b68c99b-a097-40c8-bfd5-df1cb660577a"

$built_on
[1] "Mon Aug  6 22:46:32 UTC 2018"

>   str(resp)
List of 10
 $ url        : chr "https://localhost:8000/api/1/service/connect/1/health"
 $ status_code: int 200
 $ headers    :List of 7
 ...
 
>   resp$url
[1] "https://localhost:8000/api/1/service/connect/1/health"
```

## Model Manage Class
Model manage is cool...

## Engine Class

Engines are cool...




