#' @useDynLib FastscoreRSDK

# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -r GoSDK.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = SWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  assign(defName,  .values,  envir = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################



setClass('_p__GoString_', contains = 'ExternalReference')
setClass("_GoString_",
    representation(
        p = "character",
        n = "integer"),
        contains = "RSWIGStruct")


# End class _GoString_

setClass('_p__GoString_', contains = 'ExternalReference')
setClass('_p_GoInterface', contains = 'ExternalReference')
setClass("GoInterface",
    representation(
),
        contains = "RSWIGStruct")


# End class GoInterface

setClass('_p_GoInterface', contains = 'ExternalReference')
setClass('_p_GoSlice', contains = 'ExternalReference')
setClass("GoSlice",
    representation(
        len = "integer",
        cap = "integer"),
        contains = "RSWIGStruct")


# End class GoSlice

setClass('_p_GoSlice', contains = 'ExternalReference')



setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

suppressMessages(suppressWarnings(setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})))

# Start of _GoString__p_set

`_GoString__p_set` = function(self, s_p)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_p = as(s_p, "character"); 
  ;.Call('R_swig__GoString__p_set', self, s_p, PACKAGE='FastscoreRSDK');
  
}

attr(`_GoString__p_set`, 'returnType') = 'void'
attr(`_GoString__p_set`, "inputTypes") = c('_p__GoString_', 'character')
class(`_GoString__p_set`) = c("SWIGFunction", class('_GoString__p_set'))

# Start of _GoString__p_get

`_GoString__p_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig__GoString__p_get', self, PACKAGE='FastscoreRSDK');
  
}

attr(`_GoString__p_get`, 'returnType') = 'character'
attr(`_GoString__p_get`, "inputTypes") = c('_p__GoString_')
class(`_GoString__p_get`) = c("SWIGFunction", class('_GoString__p_get'))

# Start of _GoString__n_set

`_GoString__n_set` = function(self, s_n)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_n = as.integer(s_n);
  
  if(length(s_n) > 1) {
    warning("using only the first element of s_n");
  };
  
  ;.Call('R_swig__GoString__n_set', self, s_n, PACKAGE='FastscoreRSDK');
  
}

attr(`_GoString__n_set`, 'returnType') = 'void'
attr(`_GoString__n_set`, "inputTypes") = c('_p__GoString_', 'integer')
class(`_GoString__n_set`) = c("SWIGFunction", class('_GoString__n_set'))

# Start of _GoString__n_get

`_GoString__n_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig__GoString__n_get', self, as.logical(.copy), PACKAGE='FastscoreRSDK');
  
}

attr(`_GoString__n_get`, 'returnType') = 'integer'
attr(`_GoString__n_get`, "inputTypes") = c('_p__GoString_')
class(`_GoString__n_get`) = c("SWIGFunction", class('_GoString__n_get'))

# Start of new__GoString_

`_GoString_` = function()
{
  ;ans = .Call('R_swig_new__GoString_', PACKAGE='FastscoreRSDK');
  ans <- new("_p__GoString_", ref=ans) ;
  
  reg.finalizer(ans@ref, delete__GoString_)
  ans
  
}

attr(`_GoString_`, 'returnType') = '_p__GoString_'
class(`_GoString_`) = c("SWIGFunction", class('_GoString_'))

# Start of delete__GoString_

`delete__GoString_` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete__GoString_', self, PACKAGE='FastscoreRSDK');
  
}

attr(`delete__GoString_`, 'returnType') = 'void'
attr(`delete__GoString_`, "inputTypes") = c('_p__GoString_')
class(`delete__GoString_`) = c("SWIGFunction", class('delete__GoString_'))

# Start of accessor method for _GoString_
setMethod('$', '_p__GoString_', function(x, name)

{
  accessorFuns = list('p' = `_GoString__p_get`, 'n' = `_GoString__n_get`);
  vaccessors = c('p', 'n');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for _GoString_
# Start of accessor method for _GoString_
setMethod('$<-', '_p__GoString_', function(x, name, value)

{
  accessorFuns = list('p' = `_GoString__p_set`, 'n' = `_GoString__n_set`);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p__GoString_', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('p' = `_GoString__p_set`, 'n' = `_GoString__n_set`);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for _GoString_
setMethod('delete', '_p__GoString_', function(obj) {delete__GoString_(obj)})
# Start definition of copy functions & methods for _GoString_
CopyToR__GoString_ = function(value, obj = new("_GoString_"))
{
  obj@p = value$p;
  obj@n = value$n;
  obj;
}



CopyToC__GoString_ = function(value, obj)
{
  obj$p = value@p;
  obj$n = value@n;
  obj
}



# Start definition of copy methods for _GoString_
setMethod('copyToR', '_p__GoString_', CopyToR__GoString_);
setMethod('copyToC', '_GoString_', CopyToC__GoString_);

# End definition of copy methods for _GoString_
# End definition of copy functions & methods for _GoString_
# Start of GoInterface_t_set

`GoInterface_t_set` = function(self, s_t)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  if (inherits(s_t, "ExternalReference")) s_t = slot(s_t,"ref") 
  ;.Call('R_swig_GoInterface_t_set', self, s_t, PACKAGE='FastscoreRSDK');
  
}

attr(`GoInterface_t_set`, 'returnType') = 'void'
attr(`GoInterface_t_set`, "inputTypes") = c('_p_GoInterface', '_p_void')
class(`GoInterface_t_set`) = c("SWIGFunction", class('GoInterface_t_set'))

# Start of GoInterface_t_get

`GoInterface_t_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;ans = .Call('R_swig_GoInterface_t_get', self, PACKAGE='FastscoreRSDK');
  ans <- new("_p_void", ref=ans) ;
  
  ans
  
}

attr(`GoInterface_t_get`, 'returnType') = '_p_void'
attr(`GoInterface_t_get`, "inputTypes") = c('_p_GoInterface')
class(`GoInterface_t_get`) = c("SWIGFunction", class('GoInterface_t_get'))

# Start of GoInterface_v_set

`GoInterface_v_set` = function(self, s_v)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  if (inherits(s_v, "ExternalReference")) s_v = slot(s_v,"ref") 
  ;.Call('R_swig_GoInterface_v_set', self, s_v, PACKAGE='FastscoreRSDK');
  
}

attr(`GoInterface_v_set`, 'returnType') = 'void'
attr(`GoInterface_v_set`, "inputTypes") = c('_p_GoInterface', '_p_void')
class(`GoInterface_v_set`) = c("SWIGFunction", class('GoInterface_v_set'))

# Start of GoInterface_v_get

`GoInterface_v_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;ans = .Call('R_swig_GoInterface_v_get', self, PACKAGE='FastscoreRSDK');
  ans <- new("_p_void", ref=ans) ;
  
  ans
  
}

attr(`GoInterface_v_get`, 'returnType') = '_p_void'
attr(`GoInterface_v_get`, "inputTypes") = c('_p_GoInterface')
class(`GoInterface_v_get`) = c("SWIGFunction", class('GoInterface_v_get'))

# Start of new_GoInterface

`GoInterface` = function()
{
  ;ans = .Call('R_swig_new_GoInterface', PACKAGE='FastscoreRSDK');
  ans <- new("_p_GoInterface", ref=ans) ;
  
  reg.finalizer(ans@ref, delete_GoInterface)
  ans
  
}

attr(`GoInterface`, 'returnType') = '_p_GoInterface'
class(`GoInterface`) = c("SWIGFunction", class('GoInterface'))

# Start of delete_GoInterface

`delete_GoInterface` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_GoInterface', self, PACKAGE='FastscoreRSDK');
  
}

attr(`delete_GoInterface`, 'returnType') = 'void'
attr(`delete_GoInterface`, "inputTypes") = c('_p_GoInterface')
class(`delete_GoInterface`) = c("SWIGFunction", class('delete_GoInterface'))

# Start of accessor method for GoInterface
setMethod('$', '_p_GoInterface', function(x, name)

{
  accessorFuns = list('t' = GoInterface_t_get, 'v' = GoInterface_v_get);
  vaccessors = c('t', 'v');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for GoInterface
# Start of accessor method for GoInterface
setMethod('$<-', '_p_GoInterface', function(x, name, value)

{
  accessorFuns = list('t' = GoInterface_t_set, 'v' = GoInterface_v_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_GoInterface', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('t' = GoInterface_t_set, 'v' = GoInterface_v_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for GoInterface
setMethod('delete', '_p_GoInterface', function(obj) {delete_GoInterface(obj)})
# Start definition of copy functions & methods for GoInterface
CopyToR_GoInterface = function(value, obj = new("GoInterface"))
{
  obj;
}



CopyToC_GoInterface = function(value, obj)
{
  obj
}



# Start definition of copy methods for GoInterface
setMethod('copyToR', '_p_GoInterface', CopyToR_GoInterface);
setMethod('copyToC', 'GoInterface', CopyToC_GoInterface);

# End definition of copy methods for GoInterface
# End definition of copy functions & methods for GoInterface
# Start of GoSlice_data_set

`GoSlice_data_set` = function(self, s_data)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  if (inherits(s_data, "ExternalReference")) s_data = slot(s_data,"ref") 
  ;.Call('R_swig_GoSlice_data_set', self, s_data, PACKAGE='FastscoreRSDK');
  
}

attr(`GoSlice_data_set`, 'returnType') = 'void'
attr(`GoSlice_data_set`, "inputTypes") = c('_p_GoSlice', '_p_void')
class(`GoSlice_data_set`) = c("SWIGFunction", class('GoSlice_data_set'))

# Start of GoSlice_data_get

`GoSlice_data_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;ans = .Call('R_swig_GoSlice_data_get', self, PACKAGE='FastscoreRSDK');
  ans <- new("_p_void", ref=ans) ;
  
  ans
  
}

attr(`GoSlice_data_get`, 'returnType') = '_p_void'
attr(`GoSlice_data_get`, "inputTypes") = c('_p_GoSlice')
class(`GoSlice_data_get`) = c("SWIGFunction", class('GoSlice_data_get'))

# Start of GoSlice_len_set

`GoSlice_len_set` = function(self, s_len)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_len = as.integer(s_len);
  
  if(length(s_len) > 1) {
    warning("using only the first element of s_len");
  };
  
  ;.Call('R_swig_GoSlice_len_set', self, s_len, PACKAGE='FastscoreRSDK');
  
}

attr(`GoSlice_len_set`, 'returnType') = 'void'
attr(`GoSlice_len_set`, "inputTypes") = c('_p_GoSlice', 'integer')
class(`GoSlice_len_set`) = c("SWIGFunction", class('GoSlice_len_set'))

# Start of GoSlice_len_get

`GoSlice_len_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_GoSlice_len_get', self, as.logical(.copy), PACKAGE='FastscoreRSDK');
  
}

attr(`GoSlice_len_get`, 'returnType') = 'integer'
attr(`GoSlice_len_get`, "inputTypes") = c('_p_GoSlice')
class(`GoSlice_len_get`) = c("SWIGFunction", class('GoSlice_len_get'))

# Start of GoSlice_cap_set

`GoSlice_cap_set` = function(self, s_cap)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_cap = as.integer(s_cap);
  
  if(length(s_cap) > 1) {
    warning("using only the first element of s_cap");
  };
  
  ;.Call('R_swig_GoSlice_cap_set', self, s_cap, PACKAGE='FastscoreRSDK');
  
}

attr(`GoSlice_cap_set`, 'returnType') = 'void'
attr(`GoSlice_cap_set`, "inputTypes") = c('_p_GoSlice', 'integer')
class(`GoSlice_cap_set`) = c("SWIGFunction", class('GoSlice_cap_set'))

# Start of GoSlice_cap_get

`GoSlice_cap_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_GoSlice_cap_get', self, as.logical(.copy), PACKAGE='FastscoreRSDK');
  
}

attr(`GoSlice_cap_get`, 'returnType') = 'integer'
attr(`GoSlice_cap_get`, "inputTypes") = c('_p_GoSlice')
class(`GoSlice_cap_get`) = c("SWIGFunction", class('GoSlice_cap_get'))

# Start of new_GoSlice

`GoSlice` = function()
{
  ;ans = .Call('R_swig_new_GoSlice', PACKAGE='FastscoreRSDK');
  ans <- new("_p_GoSlice", ref=ans) ;
  
  reg.finalizer(ans@ref, delete_GoSlice)
  ans
  
}

attr(`GoSlice`, 'returnType') = '_p_GoSlice'
class(`GoSlice`) = c("SWIGFunction", class('GoSlice'))

# Start of delete_GoSlice

`delete_GoSlice` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_GoSlice', self, PACKAGE='FastscoreRSDK');
  
}

attr(`delete_GoSlice`, 'returnType') = 'void'
attr(`delete_GoSlice`, "inputTypes") = c('_p_GoSlice')
class(`delete_GoSlice`) = c("SWIGFunction", class('delete_GoSlice'))

# Start of accessor method for GoSlice
setMethod('$', '_p_GoSlice', function(x, name)

{
  accessorFuns = list('data' = GoSlice_data_get, 'len' = GoSlice_len_get, 'cap' = GoSlice_cap_get);
  vaccessors = c('data', 'len', 'cap');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for GoSlice
# Start of accessor method for GoSlice
setMethod('$<-', '_p_GoSlice', function(x, name, value)

{
  accessorFuns = list('data' = GoSlice_data_set, 'len' = GoSlice_len_set, 'cap' = GoSlice_cap_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_GoSlice', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('data' = GoSlice_data_set, 'len' = GoSlice_len_set, 'cap' = GoSlice_cap_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for GoSlice
setMethod('delete', '_p_GoSlice', function(obj) {delete_GoSlice(obj)})
# Start definition of copy functions & methods for GoSlice
CopyToR_GoSlice = function(value, obj = new("GoSlice"))
{
  obj@len = value$len;
  obj@cap = value$cap;
  obj;
}



CopyToC_GoSlice = function(value, obj)
{
  obj$len = value@len;
  obj$cap = value@cap;
  obj
}



# Start definition of copy methods for GoSlice
setMethod('copyToR', '_p_GoSlice', CopyToR_GoSlice);
setMethod('copyToC', 'GoSlice', CopyToC_GoSlice);

# End definition of copy methods for GoSlice
# End definition of copy functions & methods for GoSlice


# Start of Attachment_upload
#' Upload an attqchment to a model from local path
#' @export
#' @param model_name model name
#' @param att_name attachment name
#' @param att_path path of the attachment (inluding file name)
#' @return operation message or error message
`Attachment_upload` = function(model_name, att_name, att_path)
{
  p0 = as(model_name, "character"); 
  p1 = as(att_name, "character"); 
  p2 = as(att_path, "character"); 
  ;.Call('R_swig_Attachment_upload', p0, p1, p2, PACKAGE='FastscoreRSDK');
  
}

attr(`Attachment_upload`, 'returnType') = 'character'
attr(`Attachment_upload`, "inputTypes") = c('character', 'character', 'character')
class(`Attachment_upload`) = c("SWIGFunction", class('Attachment_upload'))

# Start of Attachment_download
#' Download an attachment to a local path
#' @export
#' @param model_name model name
#' @param att_name attachment name
#' @param att_path path of the attachment (inluding file name)
#' @return operation message or error message
`Attachment_download` = function(model_name, att_name, att_path)
{
  p0 = as(model_name, "character"); 
  p1 = as(att_name, "character"); 
  p2 = as(att_path, "character");
  ;.Call('R_swig_Attachment_download', p0, p1, p2, PACKAGE='FastscoreRSDK');
  
}

attr(`Attachment_download`, 'returnType') = 'character'
attr(`Attachment_download`, "inputTypes") = c('character', 'character', 'character')
class(`Attachment_download`) = c("SWIGFunction", class('Attachment_download'))

# Start of Attachment_list
#' List all attchments of a model
#' @export
#' @param model_name name of the model to check for attachments
#' @return list of names or error message
`Attachment_list` = function(model_name)
{
  p0 = as(model_name, "character"); 
  ;ans = .Call('R_swig_Attachment_list', p0, PACKAGE='FastscoreRSDK');
  ans <- StringToList(ans)
  ans
}

attr(`Attachment_list`, 'returnType') = 'character'
attr(`Attachment_list`, "inputTypes") = c('character')
class(`Attachment_list`) = c("SWIGFunction", class('Attachment_list'))

# Start of Attachment_remove
#' Remove an attachment from a model
#' @export
#' @param model_name model name
#' @param att_name attachment name
#' @return operation message or error message
`Attachment_remove` = function(model_name, att_name)
{
  p0 = as(model_name, "character"); 
  p1 = as(att_name, "character"); 
  ;.Call('R_swig_Attachment_remove', p0, p1, PACKAGE='FastscoreRSDK');
  
}

attr(`Attachment_remove`, 'returnType') = 'character'
attr(`Attachment_remove`, "inputTypes") = c('character', 'character')
class(`Attachment_remove`) = c("SWIGFunction", class('Attachment_remove'))

# Start of Config_show
#' Show configuration of Fastscore
#' @export
#' @return instance info or error message
`Config_show` = function()
{
  ;.Call('R_swig_Config_show', PACKAGE='FastscoreRSDK');
  
}

attr(`Config_show`, 'returnType') = 'character'
class(`Config_show`) = c("SWIGFunction", class('Config_show'))

# Start of Config_set
#' Set configuration from a local file
#' @export
#' @param path path of the configuration file
#' @return operation message or error message
`Config_set` = function(path)
{
  p0 = as(path, "character"); 
  ;.Call('R_swig_Config_set', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Config_set`, 'returnType') = 'character'
attr(`Config_set`, "inputTypes") = c('character')
class(`Config_set`) = c("SWIGFunction", class('Config_set'))

# Start of Connect
#' Connect to Fastscore, set proxy_prefix
#' @export
#' @param proxy_prefix prefix of connect
#' @return proxy prefix + built date or error message
`Connect` = function(proxy_prefix)
{
  p0 = as(proxy_prefix, "character"); 
  ;.Call('R_swig_Connect', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Connect`, 'returnType') = 'character'
attr(`Connect`, "inputTypes") = c('character')
class(`Connect`) = c("SWIGFunction", class('Connect'))

# Start of Engine_inspect
#' Inspect an engine
#' @export
#' @param name engine name
#' @return instance info or error message
`Engine_inspect` = function(name)
{
  p0 = as(name, "character"); 
  ;.Call('R_swig_Engine_inspect', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Engine_inspect`, 'returnType') = 'character'
attr(`Engine_inspect`, "inputTypes") = c('character')
class(`Engine_inspect`) = c("SWIGFunction", class('Engine_inspect'))

# Start of Engine_pause
#' Pause an engine
#' @export
#' @param name engine name
#' @return operation message or error message
`Engine_pause` = function(name)
{
  p0 = as(name, "character"); 
  ;.Call('R_swig_Engine_pause', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Engine_pause`, 'returnType') = 'character'
attr(`Engine_pause`, "inputTypes") = c('character')
class(`Engine_pause`) = c("SWIGFunction", class('Engine_pause'))

# Start of Engine_unpause
#' Unpause an engine
#' @export
#' @param name engine name
#' @return operation message or error message
`Engine_unpause` = function(name)
{
  p0 = as(name, "character"); 
  ;.Call('R_swig_Engine_unpause', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Engine_unpause`, 'returnType') = 'character'
attr(`Engine_unpause`, "inputTypes") = c('character')
class(`Engine_unpause`) = c("SWIGFunction", class('Engine_unpause'))

# Start of Engine_reset
#' Reset an engine, or reset all engines
#' @export
#' @param name engine name, "all" to reset all engines
#' @return operation message or error message
`Engine_reset` = function(name_or_all)
{
  p0 = as(name_or_all, "character"); 
  ;.Call('R_swig_Engine_reset', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Engine_reset`, 'returnType') = 'character'
attr(`Engine_reset`, "inputTypes") = c('character')
class(`Engine_reset`) = c("SWIGFunction", class('Engine_reset'))

# Start of Get_Fleet
#' Show all fleets and health
#' @export
#' @return list of name + health or error message
`Get_Fleet` = function()
{
  ;ans = .Call('R_swig_Get_Fleet', PACKAGE='FastscoreRSDK');
  ans <- StringToList(ans)
  ans
  
}

attr(`Get_Fleet`, 'returnType') = 'character'
class(`Get_Fleet`) = c("SWIGFunction", class('Get_Fleet'))

# Start of Model_add
#' Add a model from local file
#' @export
#' @param name model name
#' @param path model path (including file name)
#' @return operation message or error message
`Model_add` = function(name, path)
{
  p0 = as(name, "character"); 
  p1 = as(path, "character"); 
  ;.Call('R_swig_Model_add', p0, p1, PACKAGE='FastscoreRSDK');
  
}

attr(`Model_add`, 'returnType') = 'character'
attr(`Model_add`, "inputTypes") = c('character', 'character')
class(`Model_add`) = c("SWIGFunction", class('Model_add'))

# Start of Model_show
#' Show content of a model
#' @export
#' @param name model name
#' @return instance info or error message
`Model_show` = function(name)
{
  p0 = as(name, "character"); 
  ;.Call('R_swig_Model_show', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Model_show`, 'returnType') = 'character'
attr(`Model_show`, "inputTypes") = c('character')
class(`Model_show`) = c("SWIGFunction", class('Model_show'))

# Start of Model_list
#' List all models
#' @export
#' @return list of names or error message
`Model_list` = function()
{
  ;ans = .Call('R_swig_Model_list', PACKAGE='FastscoreRSDK');
  ans <- StringToList(ans)
  ans
  
}

attr(`Model_list`, 'returnType') = 'character'
class(`Model_list`) = c("SWIGFunction", class('Model_list'))

# Start of Model_remove
#' Remove a model
#' @export
#' @param name model name
#' @return operation message or error message
`Model_remove` = function(name)
{
  p0 = as(name, "character"); 
  ;.Call('R_swig_Model_remove', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Model_remove`, 'returnType') = 'character'
attr(`Model_remove`, "inputTypes") = c('character')
class(`Model_remove`) = c("SWIGFunction", class('Model_remove'))

# Start of Model_load
#' Load a model to an engine
#' @export 
#' @param model_name model name
#' @param engine_name model name
#' @return operation message or error message
`Model_load` = function(model_name, engine_name)
{
  p0 = as(model_name, "character"); 
  p1 = as(engine_name, "character"); 
  ;.Call('R_swig_Model_load', p0, p1, PACKAGE='FastscoreRSDK');
  
}

attr(`Model_load`, 'returnType') = 'character'
attr(`Model_load`, "inputTypes") = c('character', 'character')
class(`Model_load`) = c("SWIGFunction", class('Model_load'))

# Start of Model_inspect
#' Inspect a model
#' @export
#' @param name model name
#' @return instance info or error message
`Model_inspect` = function(name)
{
  p0 = as(name, "character"); 
  ;ans = .Call('R_swig_Model_inspect', p0, PACKAGE='FastscoreRSDK');
  ans <- StringToList(ans)
  ans
}

attr(`Model_inspect`, 'returnType') = 'character'
attr(`Model_inspect`, "inputTypes") = c('character')
class(`Model_inspect`) = c("SWIGFunction", class('Model_inspect'))

# Start of Model_input
#' Send input to a (rest) engine slot
#' @export
#' @param engine_name engine name
#' @param slot engine slot to put input
#' @return instance info or error message
`Model_input` = function(engine_name, slot)
{
  p0 = as(engine_name, "character"); 
  p1 = as.integer(slot);
  
  if(length(p1) > 1) {
    warning("using only the first element of p1");
  };
  
  ;.Call('R_swig_Model_input', p0, p1, PACKAGE='FastscoreRSDK');
  
}

attr(`Model_input`, 'returnType') = 'character'
attr(`Model_input`, "inputTypes") = c('character', 'integer')
class(`Model_input`) = c("SWIGFunction", class('Model_input'))

# Start of Model_output
# Listen for model outputs from a (rest) engine slot
#' @export
#' @param engine_name engine name
#' @param slot output slot
`Model_output` = function(engine_name, slot)
{
  p0 = as(slot, "character"); 
  p1 = as.integer(slot);
  
  if(length(p1) > 1) {
    warning("using only the first element of p1");
  };
  
  ;.Call('R_swig_Model_output', p0, p1, PACKAGE='FastscoreRSDK');
  
}

attr(`Model_output`, 'returnType') = 'character'
attr(`Model_output`, "inputTypes") = c('character', 'integer')
class(`Model_output`) = c("SWIGFunction", class('Model_output'))

# Start of Model_scale
# Scale a running model
#' @export
#' @param engine_name engine name
#' @param scale scale number
`Model_scale` = function(engine_name, scale)
{
  p0 = as(engine_name, "character"); 
  p1 = as.integer(scale);
  
  if(length(p1) > 1) {
    warning("using only the first element of p1");
  };
  
  ;.Call('R_swig_Model_scale', p0, p1, PACKAGE='FastscoreRSDK');
  
}

attr(`Model_scale`, 'returnType') = 'character'
attr(`Model_scale`, "inputTypes") = c('character', 'integer')
class(`Model_scale`) = c("SWIGFunction", class('Model_scale'))

# Start of Run
#' Run a model in an engine, need to specify input and output streams
#' @export
#' @param engine_name engine name
#' @param model_name model name
#' @param stream0_name input stream name
#' @param stream1_name output stream name
#' @return operation message or error message
`Run` = function(engine_name, model_name, stream0_name, stream1_name)
{
  p0 = as(engine_name, "character"); 
  p1 = as(model_name, "character"); 
  p2 = as(stream0_name, "character"); 
  p3 = as(stream1_name, "character"); 
  ;.Call('R_swig_Run', p0, p1, p2, p3, PACKAGE='FastscoreRSDK');
  
}

attr(`Run`, 'returnType') = 'character'
attr(`Run`, "inputTypes") = c('character', 'character', 'character', 'character')
class(`Run`) = c("SWIGFunction", class('Run'))

# Start of Schema_list
#' List all schemas
#' @export
#' @return list of names or error message
`Schema_list` = function()
{
  ;ans = .Call('R_swig_Schema_list', PACKAGE='FastscoreRSDK');
  ans <- StringToList(ans)
  ans
}

attr(`Schema_list`, 'returnType') = 'character'
class(`Schema_list`) = c("SWIGFunction", class('Schema_list'))

# Start of Schema_show
#' Show content of a schema
#' @export
#' @return instance info or error message
`Schema_show` = function(p0)
{
  p0 = as(p0, "character"); 
  ;.Call('R_swig_Schema_show', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Schema_show`, 'returnType') = 'character'
attr(`Schema_show`, "inputTypes") = c('character')
class(`Schema_show`) = c("SWIGFunction", class('Schema_show'))

# Start of Schema_add
#' Add a schema from local path
#' @export
#' @param name schema name
#' @param path path of file (including file name)
#' @return operation message or error message
`Schema_add` = function(name, path)
{
  p0 = as(name, "character"); 
  p1 = as(path, "character"); 
  ;.Call('R_swig_Schema_add', p0, p1, PACKAGE='FastscoreRSDK');
  
}

attr(`Schema_add`, 'returnType') = 'character'
attr(`Schema_add`, "inputTypes") = c('character', 'character')
class(`Schema_add`) = c("SWIGFunction", class('Schema_add'))

# Start of Schema_remove
#' Remove a schema
#' @export
#' @param name schema name
#' @return operation message or error message
`Schema_remove` = function(name)
{
  p0 = as(name, "character"); 
  ;.Call('R_swig_Schema_remove', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Schema_remove`, 'returnType') = 'character'
attr(`Schema_remove`, "inputTypes") = c('character')
class(`Schema_remove`) = c("SWIGFunction", class('Schema_remove'))

# Start of Stream_show
#' Show content of a stream
#' @export
#' @param name stream name
#' @return instance info or error message
`Stream_show` = function(name)
{
  p0 = as(name, "character"); 
  ;.Call('R_swig_Stream_show', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Stream_show`, 'returnType') = 'character'
attr(`Stream_show`, "inputTypes") = c('character')
class(`Stream_show`) = c("SWIGFunction", class('Stream_show'))

# Start of Stream_list
#' List all streams
#' @export
#' @return list of names or error message
`Stream_list` = function()
{
  ;ans = .Call('R_swig_Stream_list', PACKAGE='FastscoreRSDK');
  ans <- StringToList(ans)
  ans
}

attr(`Stream_list`, 'returnType') = 'character'
class(`Stream_list`) = c("SWIGFunction", class('Stream_list'))

# Start of Stream_add
#' Add a stream from local file
#' @export
#' @param name stream name
#' @param path stream file path (including file name)
#' @return operation message or error message
`Stream_add` = function(name, path)
{
  p0 = as(name, "character"); 
  p1 = as(path, "character"); 
  ;.Call('R_swig_Stream_add', p0, p1, PACKAGE='FastscoreRSDK');
  
}

attr(`Stream_add`, 'returnType') = 'character'
attr(`Stream_add`, "inputTypes") = c('character', 'character')
class(`Stream_add`) = c("SWIGFunction", class('Stream_add'))

# Start of Stream_remove
#' Remove a stream
#' @export
#' @param name stream name
#' @return operation message or error message
`Stream_remove` = function(name)
{
  p0 = as(name, "character"); 
  ;.Call('R_swig_Stream_remove', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Stream_remove`, 'returnType') = 'character'
attr(`Stream_remove`, "inputTypes") = c('character')
class(`Stream_remove`) = c("SWIGFunction", class('Stream_remove'))

# Start of Stream_attach
#' Attach a stream to an engine, specify slot
#' @export
#' @param stream_name stream name
#' @param engine_name engine name
#' @param slot attach slot number
#' @return operation message or error message
`Stream_attach` = function(slot, stream_name, engine_name)
{
  p0 = as.integer(slot);
  
  if(length(p0) > 1) {
    warning("using only the first element of p0");
  };
  
  p1 = as(stream_name, "character"); 
  p2 = as(engine_name, "character"); 
  ;.Call('R_swig_Stream_attach', p0, p1, p2, PACKAGE='FastscoreRSDK');
  
}

attr(`Stream_attach`, 'returnType') = 'character'
attr(`Stream_attach`, "inputTypes") = c('integer', 'character', 'character')
class(`Stream_attach`) = c("SWIGFunction", class('Stream_attach'))

# Start of Stream_detach
# detach any stream attached to an engine, specify slot
#' @export
#' @param slot detach slot number
#' @param engine_name engine name
#' @return operation message or error message
`Stream_detach` = function(slot, engine_name)
{
  p0 = as.integer(slot);
  
  if(length(p0) > 1) {
    warning("using only the first element of p0");
  };
  
  p1 = as(engine_name, "character"); 
  ;.Call('R_swig_Stream_detach', p0, p1, PACKAGE='FastscoreRSDK');
  
}

attr(`Stream_detach`, 'returnType') = 'character'
attr(`Stream_detach`, "inputTypes") = c('integer', 'character')
class(`Stream_detach`) = c("SWIGFunction", class('Stream_detach'))

# Start of Stream_inspect
#' Inspect a stream
#' @export
#' @param stream_name stream name
#' @param engine_name engine name
#' @return instance info or error message
`Stream_inspect` = function(stream_name, engine_name)
{
  p0 = as(stream_name, "character"); 
  p1 = as(engine_name, "character"); 
  ;.Call('R_swig_Stream_inspect', p0, p1, PACKAGE='FastscoreRSDK');
  
}

attr(`Stream_inspect`, 'returnType') = 'character'
attr(`Stream_inspect`, "inputTypes") = c('character', 'character')
class(`Stream_inspect`) = c("SWIGFunction", class('Stream_inspect'))

# Start of Stream_sample
#' Get samples from a stream, specify count
#' @export
#' @param stream_name stream name
#' @param engine_name engine name
#' @param count number of samples
#' @return samples or error message
`Stream_sample` = function(stream_name, engine_name, count)
{
  p0 = as(stream_name, "character"); 
  p1 = as(engine_name, "character"); 
  p2 = as.integer(count);
  
  if(length(p2) > 1) {
    warning("using only the first element of p2");
  };
  
  ;.Call('R_swig_Stream_sample', p0, p1, p2, PACKAGE='FastscoreRSDK');
  
}

attr(`Stream_sample`, 'returnType') = 'character'
attr(`Stream_sample`, "inputTypes") = c('character', 'character', 'integer')
class(`Stream_sample`) = c("SWIGFunction", class('Stream_sample'))

# Start of Use
#' Use a certain engine
#' @export
#' @param engine_name engine name
#' @return operation message or error message
`Use` = function(engine_name)
{
  p0 = as(engine_name, "character"); 
  ;.Call('R_swig_Use', p0, PACKAGE='FastscoreRSDK');
  
}

attr(`Use`, 'returnType') = 'character'
attr(`Use`, "inputTypes") = c('character')
class(`Use`) = c("SWIGFunction", class('Use'))


